name: Deploy (Docusaurus)

on:
  push:
    branches: [ docusaurus ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch all history for all branches and tags
        token: ${{ secrets.PAT }}

    - uses: mymindstorm/setup-emsdk@v14
      with: 
        version: 3.1.64

    - name: build
      run: .github/scripts/build_docusaurus.sh